---
title: "Improving on SOC storage models "
author: "**Rick Venema & Bas Kasemir**"
date: "`r Sys.Date()`"

output: 
  pdf_document:
    toc: False
    number_sections: True
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```
\begin{abstract}
SOC storage models can give better insights in the amount of carbon in the soil. Existing models are not versatile. Existing models were examined to make them usable for further work with the models. Eventually a lot of the model could be simplified, there were however parts that could not be simplified. We used the model from Cardinael et al. (2018)\cite{Cardinael18}. This model represents the SOC storage in the soil. The model was taken apart and the parts were examined to understand the code and what it does. The first idea was to add a nitrogen model to the code, this was however not possible due to the hard coded model. After trying to rewrite parts of the code, the factor time came across our path. This paper only gives a better insight at the model from Cardinael et al. (2018)\cite{Cardinael18}. Only a full understanding of this model can give better insights in how the model could be processed to be more efficient and versatile for use in other applications. The possibilities are available, the only obstacle is making models suited for combining. After a complete versatile model is created, we can reduce costs in agriculture by a huge amount, this is because the amount of fertilizer can be tweaked to the exact needs of the soil.
\end{abstract}

***

\twocolumn

# Introduction

Organic carbon in the soil is very important in good yield of products produced by the soil. A better understanding of organic carbon in the soil can give more insights in improving the yield of agricultural plots. Models for organic carbon storage exists, these models represent an existing agroforestry plot.
This paper extends the SOC (soil organic carbon) storage model by Cardinael et al.\cite{Cardinael18}. This model describes the flow of carbon in an agroforestry plot. The model of Cardinael et al 2018\cite{Cardinael18}. was however a hardcoded model. To be able to extend the model and use it for different locations, the model has to be improved on to be more versatile and more flexible. This can be done by rewriting big parts of the code and making tweaking parameters easier. The model used in this paper is based on the SOC storage in an agroforestry plot. When adapting this model it can be used more in normal agriculture. 
  
A lot of fertilizer is used every year by farmers all around the globe, this can be reduced if the understanding the needs of the soil increases. This fertilizer is used because the yields of the agricultural plots will otherwise decrease. Efficient use of fertilizer can also give an increased yield, this is useful because with the growing world population, every mouth needs to be fed. This can only be done if we understand the soil better and can adjust the yield to be higher. The SOC storage model by Cardinael et al.\cite{Cardinael18} gives insights that models can be created based around the soil nutrients, this can be further developed to create more models based around nutrients in the soil. These models combined can give new insights for farmers to have better yields..

# Methods
## The model

The model is defined in the paper by Cardinael et al. (2018), this model follows a three pool model. This three pool model is based on an existing 2 pool model from Guenet et al. (2013)\cite{Guenet13}.

The fresh organic compound (FOC) difference can be found in formula \ref{eq:deltafoc}. This formula calculates the difference of FOC. This is calculated by using the input of carbon, given by $I_{t,z,d}$. This is calculated by adding all the imports from the different environmental inputs (Tree, Grass, and Crop). The parameter $f_{2}$ in formula \ref{eq:deltafoc} gives the fraction of decomposed Humified Soil Organic Carbon (HSOC) that enters the FOC pool.

\begin{equation} \label{eq:deltafoc}\
\begin{aligned}
\frac{\delta FOC_{t,z,d}}{\delta t} = I_{t,z,d} + \frac{\delta F_{AD}}{\delta z} + h * f_{2}* dec\_HSOC_{t,z,d} \\ + h *dec\_HSOC2_{tzd} - dec\_FOC_{t,z,d} 
\end{aligned}
\end{equation}

The $\frac{\delta F_{AD}}{\delta z}$ parameter in formula \ref{eq:deltafoc} corresponds to the flux of carbon in the soil that is transported downwards. This flux is given by formula \ref{eq:FAD}. In formulas \ref{eq:deltafoc}, \ref{eq:deltahsoc1}, and \ref{eq:deltahsoc2}, $h$ represents the fraction that is humified. This mechanism was developed by Elzein and Balesdent(1995)\cite{ElzBa95}.

\begin{equation} \label{eq:FAD}
  F_{AD} = F_{A} + F_{D}
\end{equation}

In formula \ref{eq:FAD} the $F_{D}$ corresponds to Fick's law. This law is represented by formula \ref{eq:fick}. In the model by Cardinael et al. \ref{Cardinael18} the tillage level is also taken into account by the use of Fick's law. This tillage level is set on depth upto 0.2 meters. This is due to the usage of agricultural machinery that mixes the top layer of the soil. 

\begin{equation} \label{eq:fick}
  F_{D} = -D * \frac{\delta ^2 C}{\delta z^2}
\end{equation}

The $F_{A}$ parameter in \ref{eq:FAD} represents the advection. This represents the flow of C in the soil. This is given by formula \ref{eq:advec}.

\begin{equation} \label{eq:advec}
  F_{A} = A * C
\end{equation}

The A parameters in formula \ref{eq:advec} represents the advection rate in mm per year. 
Formula \ref{eq:deltahsoc1} gives the difference in humified soil organic carbon (HSOC). This is calculated by using the flux described in formula \ref{eq:fick}.

\begin{equation} \label{eq:deltahsoc1}
 \frac{\delta HSOC1}{\delta t} = \frac{\delta F_{AD}}{\delta z} + h * f_{1} * dec\_FOC_{t,z,d} - dec\_HSOC1_{t,z,d}
\end{equation}

Formula \ref{eq:deltahsoc2} gives the difference in the second HSOC pool in the model. The difference between formula \ref{eq:deltahsoc2} and formula \ref{eq:deltahsoc1} is the fact that in formula \ref{eq:deltahsoc2} the $dec\_HSOC2_{t,z,d}$ is substracted from $dec\_HSOC1_{t,z,d}$


\begin{equation} \label{eq:deltahsoc2}
\begin{aligned}
  \frac{\delta HSOC2}{\delta t} = \frac{\delta F_{AD}}{\delta z} + h * (1-f_{1} * dec\_FOC_{t,z,d} \\  + h *(1-f_{2})*dec\_HSOC1_{t,z,d} - dec\_HSOC2_{t,z,d}
\end{aligned}
\end{equation}

## Understanding the model

The model was taken apart for better understanding of the code and its functions. The model was divided into several parts which each correspond to a parameter or group of parameters. After dividing the code into chunks the inputs and outputs of the chunks were examined to get a better understanding of the model. 



# Results

The code was after looking at the code divided into X parts. 

## Bulk density

if statements

## Moyano et al. model

After looking at the model, the parameters were moved to a separate file, like the model by Moyano et al. 2012\cite{Moyano12}. This model was used to calculate the moist in the clay. 

grafieken met onderschrift en uitleg over wat er te zien is

## SOC stocks


## Roots profile



# Discussion

The model by Cardinael et al. 2018 \cite{Cardinael18} was a hard model to rewrite. This was eventually not done due to time issues. The code was taken apart en examined and we understand it completely. We wanted to add a nitrogen model to the model to extend the existing model to be more versatile and be able to tell more about the soil. This was not done, due to the hard coded model that we took apart. After trying to rewrite the model we came across the limit of time. This low amount of time resulted into the fact that we were not able to rewrite the model. When we found out that we wouldn't be able to rewrite it in time, we decided to take apart the code completely and making further research easier. This was due to the fact that the model was not suited for extending with other models. 
  
The model can be eventually used in different and expanding studies. The model is very interesting because a lot of soil data is collected yearly and can be used to give a better understanding of the needs of the agricultural plot. When adding a nitrogen model, the model can be used in more situations and give better insights in the status of the agricultural plot. There are a lot of different soil models that can be combined with the SOC model, these are for example, the phosphate model, the potassium model, and salt models. 


 conclusie van het verhaal, hoe was het goed uit te voeren?, waarom niet helemaal belicht, verschil.


# Conclusion
The model gives a good indication what is possible with modeling resources available in the soi, however this model only gives the carbon and is only a representation of the plots used in Cardinael et al. \cite{Cardinael18}. Afeter understanding the model the problems of the model where highlighted to make adapting this model easier. This model gives a good indication what is possible but can not be used directly to contain more resources available in the soil. 
  
This model can open up paths to modeling complete agricultural plots with their resources. This resources are important in understanding and bettering yield of the crops. A lot of fertilizer is used in agriculture, with understanding the needs of the soil, we can use our fertilizers more responsive and will reduce the impact of fertilizer on the ecosystem. 

\begin{thebibliography}{9}

\bibitem{Cardinael18}
Cardinael, R., Guenet, B., Chevallier, T., Dupraz, C., Cozzi, T., and Chenu, C.: \textit{High organic imputs explain shallow and deep SOC storage in a long-term agroforestry system - combining experimental and modeling approaches}, Biogeosciences, 15, 297-317, https://di.org/10.5194/bg-15-297-2018, 2018.

\bibitem{Soertaert10} 
Soetaert, K., Petzoldt, T., and Woodrow Setzer, R.: \textit{Solving differential equations in R: package deSolve}, J. Stat. Softw., 33, 1-25, 2010.

\bibitem{Moyano12}
Moyano, F. E., Vasilyeva, N., Bouckaert, L., Cook, F., Craine, J., Curiel Yuste, J., Don, A., Epron, D., Formanek, P., Franzluebbers, A., Ilstedt, U., K???tterer, T., Orchard, V., Reichstein, M., Rey, A., Ruamps, L., Subke, J.-A., Thomsen, I. K., and Chenu, C.:\textit{ The moisture response of soil heterotrophic respiration: interaction with soil properties}, Biogeosciences, 9, 1173-1182, https://doi.org/10.5194/bg-9-1173-2012, 2012.

\bibitem{Guenet13}
Guenet, B., Eglin, T., Vasilyeva, N., Peylin, P., Ciais, P., and Chenu, C.: \textit{The relative importance of decomposition and transport mechanisms in accounting for soil organic carbon pro???les}, Biogeosciences, 10, 2379-2392, https://doi.org/10.5194/bg-102379-2013, 2013.

\bibitem{ElzBa95}
Elzein, A. and Balesdent, J.:\textit{Mechanistic simulation of vertical distribution of carbon concentrations and residence times in soils}, Soil Sci. Soc. Am. J., 59, 1328-1335, 1995.
\end{thebibliography}
\onecolumn















