---
title: "Les 1"
author: "Bas Kasemir & Rick venema"
date: "25-04-2018"
output:
  pdf_document:
    latex_engine: xelatex
    toc: true
    toc_depth: 2
    highlight: tango
geometry: margin=0.65in
mainfont: Lato-Light
sansfont: Lato-Regular
romanfont: Lato-Light
monofont: NotoMono-Regular.ttf
---

# Les 1 Opdrachten
## 1.0 Experiment
**[1] Welke parameters (constantes) zitten er in de vergelijking?**
• Het aantal toevoegen per tijdseenheid (10)
• Het percentage dat er vanaf moet worden gehaald (0.1)
**[2] Welke variabele uit de vergelijking veranderd steeds?**
Het aantal dat op de schaal ligt.
**[3] Wat is de initiele waarde van de variabele uit vraag 2?**
10
**[4] Wat is het tijdsframe van dit experiment? (t = 0 tot t = ……. )**
t = 0 tot t = 25
**[5] Wanneer is het evenwichtsmoment?**
Bij t = 25
**[6] Uit welke variabele uit de vergelijking kunnen we dat aflezen?**
dY(?)


## 2.0 Programmeer opdracht
``` {r 2.0}
library(deSolve)

parameters <- c(addVolume = 10, pV = 0.1) 

volume <- function(t, y, parms){
  with(as.list(c(parms)), {
      dY <- addVolume - pV * (y)
      return(list(c(dY)))
    }
  )
}

#initial state
state <- c(Volume = 10)

#define time sequence you want to run the model
times <- seq(0, 300,  by = 1)

# run simulation using continuous approach
out  <- ode(times = times, y = state,   parms = parameters, func = volume, method = "euler")

#Print de uitkomst
head(out)

#plot de uitkomst
plot(out)
```

### Beantwoord de volgende vragen
**[1] Verander de parameters. Wat is het effect?**
  
  Hoe groter de parameters, hoe steiler de grafiek. (En vice versa).
  
**[2] Verander de initiële waarde. Wat is het effect?**
  
  Hierdoor zal er meer verdwijnen per tijdsstap. Ook krijgt de y-as een andere verdeling die bij deze nieuwe waarde begint.
  
**[3] Verander de timeframe. Wat is het effect?**
  Het duurt minder lang om hetzelfde effect te bereiken.
  
**[4] Verander het originele model zodat de correctie niet is op basis van (y+addVolume) maar y. Wanneer is er nu een evenwichts toestand?**

## 3.0 Oefenen met de tutorial






